# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_convertWindow(object):
    def convertWindowSetupUi(self, convertWindow):
        convertWindow.setObjectName("convertWindow")
        convertWindow.resize(1024, 600)
        convertWindow.setMaximumSize(QtCore.QSize(1024, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainWindow_ico/mainWindow_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        convertWindow.setWindowIcon(icon)
        convertWindow.setStyleSheet("background-color:rgb(195, 227, 218)")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(convertWindow)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_main_but = QtWidgets.QPushButton(convertWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_main_but.sizePolicy().hasHeightForWidth())
        self.back_main_but.setSizePolicy(sizePolicy)
        self.back_main_but.setMinimumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.back_main_but.setFont(font)
        self.back_main_but.setStyleSheet("background-color:rgb(125, 200, 203);\n"
"border-radius: 3px;")
        self.back_main_but.setObjectName("back_main_but")
        self.horizontalLayout_2.addWidget(self.back_main_but)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.videoLabel = QtWidgets.QLabel(convertWindow)
        self.videoLabel.setStyleSheet("border-radius: 5px;\n"
"\n"
"")
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.horizontalLayout_3.addWidget(self.videoLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kind_text_label = QtWidgets.QLabel(convertWindow)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.kind_text_label.setFont(font)
        self.kind_text_label.setObjectName("kind_text_label")
        self.horizontalLayout.addWidget(self.kind_text_label)
        self.price_text_label = QtWidgets.QLabel(convertWindow)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.price_text_label.setFont(font)
        self.price_text_label.setStyleSheet("")
        self.price_text_label.setObjectName("price_text_label")
        self.horizontalLayout.addWidget(self.price_text_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.resultTableWidget = QtWidgets.QTableWidget(convertWindow)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.resultTableWidget.setFont(font)
        self.resultTableWidget.setStyleSheet("background-color:rgb(195, 227, 218);\n"
"border-radius:5px;\n"
"")
        self.resultTableWidget.setAutoScrollMargin(27)
        self.resultTableWidget.setColumnCount(0)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setRowCount(0)
        self.resultTableWidget.horizontalHeader().setVisible(False)
        self.resultTableWidget.horizontalHeader().setHighlightSections(False)
        self.resultTableWidget.verticalHeader().setVisible(False)
        self.resultTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.resultTableWidget.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.resultTableWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(convertWindow)
        QtCore.QMetaObject.connectSlotsByName(convertWindow)

    def retranslateUi(self, convertWindow):
        _translate = QtCore.QCoreApplication.translate
        convertWindow.setWindowTitle(_translate("convertWindow", "回收"))
        self.back_main_but.setText(_translate("convertWindow", "返回"))
        self.kind_text_label.setText(_translate("convertWindow", "种类"))
        self.price_text_label.setText(_translate("convertWindow", "价格"))
import ico_src_rc
