# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kindWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kindWindow(object):
    def kindWindowSetupUi(self, kindWindow):
        kindWindow.setObjectName("kindWindow")
        kindWindow.resize(1024, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(kindWindow.sizePolicy().hasHeightForWidth())
        kindWindow.setSizePolicy(sizePolicy)
        kindWindow.setMaximumSize(QtCore.QSize(1024, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainWindow_ico/title_recycle_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        kindWindow.setWindowIcon(icon)
        kindWindow.setStyleSheet("background-color:rgb(195, 227, 218)")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(kindWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_main_but = QtWidgets.QPushButton(kindWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_main_but.sizePolicy().hasHeightForWidth())
        self.back_main_but.setSizePolicy(sizePolicy)
        self.back_main_but.setMinimumSize(QtCore.QSize(90, 40))
        self.back_main_but.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.back_main_but.setFont(font)
        self.back_main_but.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(125, 200, 203);\n"
"")
        self.back_main_but.setObjectName("back_main_but")
        self.horizontalLayout_2.addWidget(self.back_main_but)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.kind_infortion_table = QtWidgets.QTableWidget(kindWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kind_infortion_table.sizePolicy().hasHeightForWidth())
        self.kind_infortion_table.setSizePolicy(sizePolicy)
        self.kind_infortion_table.setStyleSheet("border-radius: 5px;\n"
"")
        self.kind_infortion_table.setObjectName("kind_infortion_table")
        self.kind_infortion_table.setColumnCount(3)
        self.kind_infortion_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        item.setFont(font)
        self.kind_infortion_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        item.setFont(font)
        self.kind_infortion_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        item.setFont(font)
        self.kind_infortion_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.kind_infortion_table)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(kindWindow)
        QtCore.QMetaObject.connectSlotsByName(kindWindow)

    def retranslateUi(self, kindWindow):
        _translate = QtCore.QCoreApplication.translate
        kindWindow.setWindowTitle(_translate("kindWindow", "种类"))
        self.back_main_but.setText(_translate("kindWindow", "返回"))
        item = self.kind_infortion_table.horizontalHeaderItem(0)
        item.setText(_translate("kindWindow", "种类"))
        item = self.kind_infortion_table.horizontalHeaderItem(1)
        item.setText(_translate("kindWindow", "名称"))
        item = self.kind_infortion_table.horizontalHeaderItem(2)
        item.setText(_translate("kindWindow", "价格"))
import ico_src_rc
